---
# tasks file for roles/terminal
- import_tasks: create-users.yml
- import_tasks: dotfiles.yml
- import_tasks: vim.yml
- import_tasks: tmux.yml
- import_tasks: fzf.yml
- import_tasks: oh-my-zsh.yml
