# delete vim if exists
- name: uninstall vim
  package:
    name: vim
    state: absent
    recurse: true
  become: true
  ignore_errors: true

# install gvim (has clipboard support)
- name: install gvim
  package:
    name: gvim
    state: present
  become: true

- name: install jellybeans
  become: yes
  become_user: '{{ item.username }}'
  command: 'git clone --depth=1 https://github.com/nanotech/jellybeans.vim.git .vim'
  args:
    chdir: '~{{ item.username }}'
    creates: '~{{ item.username }}/.vim'
  with_items: '{{ users }}'

- name: add a soft link to .vimrc
  file:
    src: '~{{ item.username }}/git_private/dotfiles/.vimrc'
    dest: '~{{ item.username }}/.vimrc'
    state: link
  with_items: '{{ users }}'
